[package]
name = "hello"
version = "0.1.0"
edition = "2024"
authors = ["NiGhT-exe"]
description = "Hello World"
repository = "https://github.com/NiGhT-exe/hello-world"
homepage = "https://github.com/NiGhT-exe/hello-world"
license = "MIT"

[dependencies]

[[bin]]
name = "hello"
